// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    copy: typeof import('./components/Notification.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    Input: typeof import('./components/Input.vue')['default']
    Item: typeof import('./components/Item.vue')['default']
    ItemList: typeof import('./components/ItemList.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    Notify: typeof import('./components/Notify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextArea: typeof import('./components/TextArea.vue')['default']
  }
}
